# Generated by Django 2.1 on 2018-08-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.Question'),
        ),
    ]
